"""empty message

Revision ID: 40ec44470922
Revises: d06ce3223c28
Create Date: 2024-02-04 21:01:06.225537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40ec44470922'
down_revision = 'd06ce3223c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchanges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codename', sa.String(length=20), nullable=False, comment='代号'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchanges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='代号'))
        batch_op.drop_column('codename')

    # ### end Alembic commands ###
