"""empty message

Revision ID: f3d8c61b841c
Revises: 40ec44470922
Create Date: 2024-02-04 21:20:05.486925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3d8c61b841c'
down_revision = '40ec44470922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchanges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=20), nullable=False, comment='代号'))
        batch_op.drop_column('codename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchanges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='代号'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
